---
title: "Connecting to leaflet API with package RAPI"
author: "Nour Qweder, Jooyoung Lee, Samia Butt"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
  toc: true

vignette: >
  %\VignetteIndexEntry{Connecting to leaflet API with package RAPI package in R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---
  ```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
---
  ```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE
)
```

```{r, include = FALSE}
library(ggmap)
library(RAPI)
```



## How to use:


```{r installation, eval = FALSE}
devtools::install_github("nourqweder/RAPI", build_vignettes = TRUE)
```



## Introduction
Depending on *Google geocode API technique* to get Location by the coordinator and vice verse, side beside with *leaflet* package to draw the map and get different display mode according to the provider from package itself.


```{r, eval = FALSE}
#  https://maps.googleapis.com/maps/api/geocode/json?parameters
```

Now, our package *RAPI* works as a  linker between the user and the Google Geocoding API. 
